BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Blogs] (
    [BlogID] NVARCHAR(1000) NOT NULL,
    [BlogTitle] NVARCHAR(1000) NOT NULL,
    [Synopsis] NVARCHAR(1000) NOT NULL,
    [FeaturedImageUrl] NVARCHAR(1000) NOT NULL,
    [Content] NVARCHAR(1000) NOT NULL,
    [IsDeleted] BIT NOT NULL CONSTRAINT [Blogs_IsDeleted_df] DEFAULT 0,
    [IsCompleted] BIT NOT NULL CONSTRAINT [Blogs_IsCompleted_df] DEFAULT 0,
    [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [Blogs_CreatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [LastUpdated] DATETIME2 NOT NULL,
    [UserID] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Blogs_pkey] PRIMARY KEY CLUSTERED ([BlogID])
);

-- AddForeignKey
ALTER TABLE [dbo].[Blogs] ADD CONSTRAINT [Blogs_UserID_fkey] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users]([UserID]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
